Burger menu
homenkovit/profitapp pull request #10
Opened 2021-10-16 19:12 UTC by norzserge

2021-10-17 12:43 UTC, homenkovit commented on src/components/popover/settings-menu/settings-menu-content/settings-menu-content.module.scss
> +  transition: all 0.1s ease;
вообще all не рекомендуется писать, но в данном случае пофиг, я думаю

2021-10-17 13:10 UTC, homenkovit requested changes

2021-10-17 13:10 UTC, homenkovit commented on src/app.tsx
> +        { /* TODO: add onHistoryClick / onDarkModeClick methods */ }
давай обернём SettingsMenu и logout в компонент top-bar-actions (название на твоё усмотрение)

и можно будет сделать `.top-bar { justify-content: space-between }`, а `.top-bar-actions { & > :not(:last-child) { margin-right: 14px } }` - будет более системно, так как мне не очень понравилось, что компонент SortBar теперь по умолчанию у тебя имеет правый маржин авто, а SettingsMenu ты прокидываешь класс-нейм только для того, чтобы ему маржин райт опять же сделать

2021-10-17 13:10 UTC, homenkovit commented on src/components/sort-bar/sort-bar.module.scss
> +  margin-right: auto;
можно будет удалить, если переделаешь структуру, предложенную мной в комментарии в app.tsx

2021-10-17 13:10 UTC, homenkovit commented on src/components/popover/popover.tsx
> +import React, { FC, ReactElement, useRef, ReactNode } from 'react';
я смотрю, ты решил с работы компонент к нам перетащить практически целиком )
снова в будущее смотришь? у нас предполагаются ещё где-то поповеры?

2021-10-19 16:39 UTC, norzserge commented on src/components/popover/settings-menu/settings-menu-content/settings-menu-content.module.scss
> +  transition: all 0.1s ease;
Поправил, но можешь пжлс кинуть статейку? Я просто не слышал, что all не рекомендован.

2021-10-19 16:43 UTC, norzserge commented on src/components/popover/settings-menu/settings-menu-content/settings-menu-content.tsx
> +          aria-label="switch color theme mode"
ок

2021-10-19 16:51 UTC, norzserge commented on src/components/popover/settings-menu/settings-menu.tsx
> +export interface SettingsMenuProps {
В смысле? Он же в компоненте используется
```
export interface SettingsMenuProps {
  className?: string;
  onHistoryClick: () => void;
  onDarkModeClick: () => void;
};

export const SettingsMenu: FC<SettingsMenuProps> = (props) => {
```

2021-10-19 17:08 UTC, norzserge commented on src/app.tsx
> +        { /* TODO: add onHistoryClick / onDarkModeClick methods */ }
Ты еще не чуешь запаха стора? X))

2021-10-19 17:31 UTC, norzserge commented on src/app.tsx
> +        { /* TODO: add onHistoryClick / onDarkModeClick methods */ }
> и можно будет сделать .top-bar { justify-content: space-between }
Для этого нужно тогда еще и оборачивать левую часть в компонент, либо в дополнительный див, т.к. получается три элемента на одном уровне, а не два (еще лейбл "сортировать по"). В общем я TopBarRightActions компонент сделал и ему задал margin-left: auto. Иначе слишком много лишних оберток появляется.

2021-10-19 20:24 UTC, homenkovit commented on src/components/popover/settings-menu/settings-menu-content/settings-menu-content.tsx
> +        <button
да, обсудим, системная, я считаю, нужна и должна быть по умолчанию, на звонке поясню, если что

2021-10-19 20:25 UTC, homenkovit commented on src/components/popover/settings-menu/settings-menu.tsx
> +export interface SettingsMenuProps {
да, я вижу, что он используется )) но зачем он нужен, я всё ещё не понимаю )
если что, давай обсудим на звонке

2021-10-19 20:25 UTC, homenkovit commented on src/components/popover/settings-menu/settings-menu.tsx
> +        aria-haspopup="true"
только это булина, и в тру должно быть только в состоянии, когда поповер виден )

2021-10-20 18:09 UTC, merged