Chart
homenkovit/profitapp pull request #5
Opened 2021-09-19 14:21 UTC by norzserge

2021-09-19 16:27 UTC, homenkovit commented on src/components/chart/chart.module.scss
> +  display: inline-flex;
везде табуляция, а здесь два пробела ))

2021-09-19 16:28 UTC, homenkovit commented on src/components/chart/chart.tsx
> +					<Tippy
забыл key по классике )

2021-09-19 16:29 UTC, homenkovit commented on src/components/chart/chart.tsx
> +							<div
давай мы див заполним данными, как в тултипе, но сделаем им visually-hidden

2021-09-19 16:31 UTC, homenkovit commented on src/components/chart/chart.tsx
> +	const planArray = props.data.map((item) => {
не хочешь сократить до однострочника?
`props.data.map((item) => item.plan);`

2021-09-19 16:33 UTC, homenkovit commented on src/components/chart/chart.tsx
> +	const definePlanColumnHeight = (planValue: number): string => planValue !== 0 ? `${planValue*100/maxPlan}%` : '3%';
в этом компоненте кажется, что не критично, но можно для оптимизации функцию эту обернуть в useCallback, а planArray и maxPlan в useMemo

2021-09-19 16:35 UTC, homenkovit commented on src/resources/pallete.scss
> +$blue-2: #1E2749;
у многих файлах есть этот значок, что, мол, не хватает пустой строки в конце файла - полагаю, что это не критично, но вроде считается нынче правилом хорошего тона, так сказать )

2021-09-19 16:40 UTC, homenkovit requested changes

2021-09-19 16:40 UTC, homenkovit commented on package.json
> +    "@tippyjs/react": "^4.2.5",
вообще мне кажется, что типпи нам в проекте в целом ни к чему, тултипы эти можно было спокойно абсолютом сделать, да и другие предполагаемые поповеры, которые у нас в планах, так же легко было бы обычными средствами css реализовать на мой взгляд, вся мощь типпи в этом проекте пока что бессмысленна, но если ты хочешь оставить, я не настаиваю )

2021-09-21 19:47 UTC, homenkovit requested changes

2021-10-02 13:03 UTC, norzserge commented on src/components/chart/chart.module.scss
> +  display: inline-flex;
поправил

2021-10-02 13:03 UTC, norzserge commented on src/components/chart/chart.tsx
> +	const planArray = props.data.map((item) => {
сократил

2021-10-02 13:04 UTC, norzserge commented on src/resources/pallete.scss
> +$blue-2: #1E2749;
а где ты этот значок видишь?

2021-10-02 13:05 UTC, norzserge commented on package.json
> +    "@tippyjs/react": "^4.2.5",
Давай оставим. Мне он очень нравится в использовании) Там на адаптивности навскидку мы можем со своими тултипами помучаться. Ребята, уверен, уже отмучились)

2021-10-02 13:06 UTC, norzserge commented on src/resources/pallete.scss
> +$blue-2: #1E2749;
Но я добавил

2021-10-02 13:17 UTC, norzserge commented on src/components/chart/chart.tsx
> +							style={{height: definePlanColumnHeight(month.plan)}}
Виталька, давай я это тебе оставлю, если ты не против) Ты у нас мастер по доступности)
Завел bire https://github.com/homenkovit/profitapp/projects/6#card-69989044

Но не очень понял, почему нам типпи не понадобиться? В нем у нас прячется подробная информация о месяце. Потенциально подсказка позже может быть расширена, я бы не хотел ограничивать ее ховером с текстом. В общем я за то, чтобы типпи оставить. Он нам еще пригодиться в будущем.

2021-10-02 13:32 UTC, norzserge commented on src/components/chart/chart.tsx
> +							<div
Сделал. Глянь, ты это имел ввиду?

2021-10-02 15:04 UTC, norzserge commented on src/components/chart/chart.tsx
> +	const definePlanColumnHeight = (planValue: number): string => planValue !== 0 ? `${planValue*100/maxPlan}%` : '3%';
Здесь не критично, да, но я обернул.

2021-10-03 12:46 UTC, homenkovit commented on src/resources/pallete.scss
> +$blue-2: #1E2749;
в интерфейсе гитхаба он отображается

2021-10-03 12:48 UTC, homenkovit commented on package.json
> +    "@tippyjs/react": "^4.2.5",
да, я понимаю, о чём ты, я об этом подумал, прежде чем коммент оставить, но у нас не увидел как раз таких кейсов на адаптивность, потому написал )

2021-10-03 12:50 UTC, homenkovit commented on src/components/chart/chart.tsx
> +							style={{height: definePlanColumnHeight(month.plan)}}
хорошо )

2021-10-03 12:52 UTC, homenkovit commented on src/components/chart/chart.tsx
> +							<div
да, думаю, так сойдёт

2021-10-03 12:59 UTC, homenkovit approved these changes

2021-10-03 13:01 UTC, merged